on: push
name: Docker Build and Push
jobs:
  dockerBuildPush:
    name: Docker Build Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u zcong --password-stdin 
        make
        make push
        echo ${{ secrets.ALI_PASSWORD }} | docker login -u ${{ secrets.ALI_USERNAME }} --password-stdin registry.cn-shanghai.aliyuncs.com
        docker tag zcong/superset:latest registry.cn-shanghai.aliyuncs.com/gymbo/superset:gymbo-0.36-05-07
        docker push registry.cn-shanghai.aliyuncs.com/gymbo/superset:gymbo-0.36-05-07
