on: push
name: Docker Build and Push
jobs:
  dockerLogin:
    name: Docker Login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      run: |
        docker login -u zcong --password-stdin ${{ secrets.DOCKER_PASSWORD }}
        make
        make push
