on: push
name: Docker Build and Push
jobs:
  dockerLogin:
    name: Docker Login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u zcong --password-stdin 
        make
        make push
